### ISSUE TITLE
data: process for tercen entree

### ISSUE THREAD

**Issue by marionlibouban** [tercen/tara_gorsky2016_data#2]

**Comment by marionlibouban** [comment]
@agouy : did you generate an additional file for this?

**Comment by agouy** [comment]
@marionlibouban what should I do to take care of this issue?

**Comment by marionlibouban** [comment]
for some project it is necessary to transform the data before its imported into tercen. if that is the case the files should be also in the repository and it should be explained in the documentation. If that is not the case then just indicate in the doc that for the project the data were in a good shape to be handled  by tercen.

**Comment by agouy** [comment]
I see better, thanks, will do.

**Comment by agouy** [comment]
@marionlibouban I added a short description of how we generated these data files here:
https://github.com/tercen/tara_gorsky2016_data
